//! Markdown rendering: one entry per section — the section's text as formatted
//! Markdown, followed by a bracket inventory table ("Option 1" layout).
//!
//! Sections with no detected brackets are skipped (nothing to fill). Guessed
//! lone-bracket spans are marked `⚠ GUESSED` in the Status column so a human reviews
//! them before relying on the file.

use std::path::Path;

use crate::detect::{BracketHit, Status};
use crate::model::{Block, Cell};
use crate::section::Section;

/// Maximum display width (in characters) for a snippet in the inventory table; longer
/// snippets (whole paragraphs, block conditions) are truncated, since their full text is
/// in the section context above.
const BRACKET_DISPLAY_MAX: usize = 60;

/// Render the detected sections of a document into a Markdown snippet file.
///
/// ```
/// use stencil::detect::detect;
/// use stencil::model::{Block, Document};
/// use stencil::section::sections;
/// use stencil::render::render;
/// use std::path::PathBuf;
///
/// let doc = Document {
///     source: PathBuf::from("contract.txt"),
///     blocks: vec![
///         Block::Heading { level: 2, text: "Payment".into() },
///         Block::Paragraph { text: "Pay [Amount].".into() },
///     ],
/// };
/// let detection = detect(&doc);
/// let md = render(&doc.source, &sections(&doc, &detection));
/// assert!(md.contains("## Payment"));
/// // The inventory snippet is the whole paragraph the bracket sits in.
/// assert!(md.contains("| `Pay [Amount].` | paired | confident |"));
/// ```
pub fn render(source: &Path, sections: &[Section<'_>]) -> String {
    let mut out = String::new();
    out.push_str(
        "<!-- Generated by Stencil — a first-pass filter, not a guarantee. \
Review ⚠ GUESSED brackets before use. -->\n",
    );
    out.push_str(&format!(
        "# Stencil — detected variables for `{}`\n\n",
        source.display()
    ));

    let mut emitted = 0usize;
    for section in sections.iter().filter(|section| section.has_hits()) {
        render_entry(&mut out, section);
        emitted += 1;
    }

    if emitted == 0 {
        out.push_str("_No bracketed variables detected._\n");
    }
    out
}

/// Render one section: its title/content, then its bracket inventory.
fn render_entry(out: &mut String, section: &Section<'_>) {
    match section.heading() {
        Some((level, text)) => {
            push_heading(out, level, text);
            for block in section.blocks.iter().skip(1) {
                render_block(out, block);
            }
        }
        None => {
            for block in &section.blocks {
                render_block(out, block);
            }
        }
    }
    render_inventory(out, &section.hits);
    out.push('\n');
}

/// Render a single block as Markdown.
fn render_block(out: &mut String, block: &Block) {
    match block {
        Block::Heading { level, text } => push_heading(out, *level, text),
        Block::Paragraph { text } => {
            out.push_str(text);
            out.push_str("\n\n");
        }
        Block::Table { rows } => render_table(out, rows),
    }
}

/// Push a Markdown heading, clamping the level to the legal 1..=6 range.
fn push_heading(out: &mut String, level: u8, text: &str) {
    let hashes = "#".repeat(level.clamp(1, 6) as usize);
    out.push_str(&format!("{hashes} {text}\n\n"));
}

/// Render a table as a Markdown grid, treating the first row as the header.
fn render_table(out: &mut String, rows: &[Vec<Cell>]) {
    let columns = rows.iter().map(Vec::len).max().unwrap_or(0);
    if columns == 0 {
        return;
    }

    let render_row = |cells: &[Cell]| -> String {
        let joined = (0..columns)
            .map(|i| {
                cells
                    .get(i)
                    .map_or(String::new(), |cell| escape_cell(&cell.text))
            })
            .collect::<Vec<_>>()
            .join(" | ");
        format!("| {joined} |\n")
    };

    out.push_str(&render_row(&rows[0]));
    out.push('|');
    for _ in 0..columns {
        out.push_str(" --- |");
    }
    out.push('\n');
    for row in &rows[1..] {
        out.push_str(&render_row(row));
    }
    out.push('\n');
}

/// Render the "Variables in this section" inventory table.
fn render_inventory(out: &mut String, hits: &[&BracketHit]) {
    out.push_str("**Variables in this section:**\n\n");
    out.push_str("| Snippet | Kind | Status |\n");
    out.push_str("|---------|------|--------|\n");
    for hit in hits {
        let status = match hit.status {
            Status::Confident => "confident",
            Status::Guessed => "⚠ GUESSED",
        };
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            format_bracket_cell(&hit.snippet),
            hit.kind.label(),
            status,
        ));
    }
}

/// Format a bracket span for a table cell: collapse whitespace, neutralize backticks,
/// truncate if long, escape pipes, and wrap in an inline-code span.
fn format_bracket_cell(span: &str) -> String {
    let collapsed = span.split_whitespace().collect::<Vec<_>>().join(" ");
    let neutralized = collapsed.replace('`', "'");
    let shortened = if neutralized.chars().count() > BRACKET_DISPLAY_MAX {
        let head: String = neutralized.chars().take(BRACKET_DISPLAY_MAX).collect();
        format!("{head}…")
    } else {
        neutralized
    };
    format!("`{}`", shortened.replace('|', "\\|"))
}

/// Escape a value for use inside a Markdown table cell.
fn escape_cell(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::detect::detect;
    use crate::model::Document;
    use crate::section::sections;
    use std::path::PathBuf;

    fn render_doc(blocks: Vec<Block>) -> String {
        let document = Document {
            source: PathBuf::from("contract.txt"),
            blocks,
        };
        let detection = detect(&document);
        render(&document.source, &sections(&document, &detection))
    }

    #[test]
    fn renders_heading_paragraph_and_inventory() {
        let md = render_doc(vec![
            Block::Heading {
                level: 2,
                text: "Payment Terms".into(),
            },
            Block::Paragraph {
                text: "The deposit is [Amount] due in [days] days.".into(),
            },
        ]);

        assert!(md.contains("## Payment Terms"));
        assert!(md.contains("The deposit is [Amount] due in [days] days."));
        assert!(md.contains("**Variables in this section:**"));
        // Both brackets share the paragraph, so both inventory rows show the whole
        // paragraph as the snippet.
        assert_eq!(
            md.matches("| `The deposit is [Amount] due in [days] days.` | paired | confident |")
                .count(),
            2
        );
    }

    #[test]
    fn guessed_brackets_are_flagged() {
        let md = render_doc(vec![Block::Paragraph {
            text: "obligations of [ the seller".into(),
        }]);
        assert!(md.contains("⚠ GUESSED"));
        assert!(md.contains("lone `[`"));
    }

    #[test]
    fn sections_without_brackets_are_skipped() {
        let md = render_doc(vec![
            Block::Heading {
                level: 1,
                text: "Boilerplate".into(),
            },
            Block::Paragraph {
                text: "Nothing to fill here.".into(),
            },
        ]);
        assert!(!md.contains("Boilerplate"));
        assert!(md.contains("_No bracketed variables detected._"));
    }

    #[test]
    fn long_bracket_span_is_truncated_in_inventory() {
        let inner = "word ".repeat(40);
        let md = render_doc(vec![Block::Paragraph {
            text: format!("[{inner}]"),
        }]);
        assert!(md.contains('…'));
        assert!(md.contains("paired (long)"));
    }

    #[test]
    fn pipes_in_bracket_are_escaped() {
        let md = render_doc(vec![Block::Paragraph {
            text: "[a | b]".into(),
        }]);
        assert!(md.contains("\\|"));
    }

    #[test]
    fn cross_paragraph_span_is_inventoried_and_flagged() {
        let md = render_doc(vec![
            Block::Paragraph {
                text: "[If the buyer defaults".into(),
            },
            Block::Paragraph {
                text: "the deposit is forfeited]".into(),
            },
        ]);
        assert!(md.contains("paired (cross-paragraph)"));
        assert!(md.contains("⚠ GUESSED"));
    }

    #[test]
    fn table_renders_as_markdown_grid() {
        let md = render_doc(vec![Block::Table {
            rows: vec![
                vec![Cell::new("Item"), Cell::new("Value")],
                vec![Cell::new("Fee"), Cell::new("[Fee]")],
            ],
        }]);
        assert!(md.contains("| Item | Value |"));
        assert!(md.contains("| --- | --- |"));
        assert!(md.contains("| Fee | [Fee] |"));
        assert!(md.contains("| `[Fee]` | paired | confident |"));
    }
}
